#!/bin/bash
# by Jeff Daube

# Todo -
# 1. Add ability to launch todone from anywhere and have file.txt source from
# ~/ directory
# 2. Add ability to prioritize items; rearange them
# 3. Upon completion: append date time to end of item


# MENU PROMPTS
#------------------------------------------------------------------------------

ADD_MENU="(a) Add an item"
DELETE_MENU="(d) Delete an item"
FINISH_MENU="(f) Finish an item"
PRIORITIZE_MENU="(p) Prioritize list"
CANCEL="\t(c) Cancel"

# GLOBAL VARIABLES
#------------------------------------------------------------------------------

ITEMS=()
FINISHED_ITEMS=()
MSG=
item_to_prioritize=-1
MODE="normal"
PURPLE_BACKGROUND="\e[45m"
RS="\e[0m"

# MENU FUNCTION DEFINITIONS
#------------------------------------------------------------------------------

function read_items_from_file () {
    ITEMS=()
    filename="file.txt"
    readarray -t lines < "$filename"
    for line in "${lines[@]}"; do
        length_of_line=${#line}
        [[ "$line" != "C "* ]] && ITEMS+=("${line}")
        [[ "$line" == "C "* ]] && FINISHED_ITEMS+=("${line:2:$length_of_line}")
    done
}

function bad_choice () { MSG="Invalid Selection ... Please Try Again" ; }

function display_msg () {
    if [ "${MSG}" ]; then
        printf "${MSG}\n"
        echo
    fi
}
function add_item () {
    echo
    show_todo_list
    echo
    printf "ADD AN ITEM\n"
    echo
    printf "$CANCEL\n"
    echo
    printf "Enter an item then press ENTER --> "
    read item
    if [[ $item -eq "c" ]]; then
        return
    else
        ITEMS+=("${item}")
    fi
}

function delete_item () { 
    number_of_list_items=${#ITEMS[@]}
    while true
    do
        echo
        show_todo_list
        echo
        printf "DELETE AN ITEM\n"
        echo
        printf "$CANCEL\n"
        echo
        display_msg
        echo
        printf "Enter an item # to delete then press ENTER --> "
        read item
        case $item in
            c|C)
                return;;
            [1-"$number_of_list_items"])    
                item_to_delete=$(($item -1))
                ITEMS=("${ITEMS[@]:0:$item_to_delete}" "${ITEMS[@]:$(($item_to_delete \
                + 1))}")
                MSG=
                return;;
            *) bad_choice;;
        esac
    done
}

function finish_item () {
    NOW=$(date +"(%Y-%m-%d - %H:%M)")
    number_of_list_items=${#ITEMS[@]}
    while true
    do
        echo
        show_todo_list
        show_finished_items
        printf "FINISH AN ITEM\n"
        echo
        printf "$CANCEL\n"
        echo
        display_msg
        echo
        printf "Enter a item # then press ENTER --> "
        read item
        case $item in
            c|C)
                return;;
            [1-"$number_of_list_items"])
                item_to_finish=$((item-1))
                FINISHED_ITEMS+=("${ITEMS[$item_to_finish]} $NOW")
                ITEMS=("${ITEMS[@]:0:$item_to_finish}" "${ITEMS[@]:$(($item_to_finish \
                + 1))}")
                MSG=
                return;;
            *) bad_choice;;
        esac
    done
}

function print_a_list ()  {
    array=("$@")
    for ((i=0; i < ${#array[@]}; ++i)); do
        position=$(( $i + 1 ))
        if [ $i == $item_to_prioritize ]; then
            printf "\t$PURPLE_BACKGROUND$position. ${array[$i]}$RS\n"
        else
            printf "\t$position. ${array[$i]}\n"
        fi
    done
}

function show_todo_list () {
    clear
    printf "\nTo-Do List:\n\n"
    print_a_list "${ITEMS[@]}"
}

function write_list_to_file () {
    export_string=
    for ((i=0; i < ${#ITEMS[@]}; ++i)); do
        export_string+="${ITEMS[$i]}\n"
    done
    for ((i=0; i < ${#FINISHED_ITEMS[@]}; ++i)); do
        export_string+="C ${FINISHED_ITEMS[$i]}\n"
    done
    printf "${export_string}" > ~/file.txt
    clear
    break
}

function show_finished_items () {
    printf "\nDone:\n\n"
    print_a_list "${FINISHED_ITEMS[@]}"
    echo
}

function show_main_menu_options () {
    echo "Commands:"
    echo
    printf "\t${ADD_MENU}\n"
    printf "\t${DELETE_MENU}\n"
    printf "\t${FINISH_MENU}\n"
    printf "\t${PRIORITIZE_MENU}\n"
    printf "\t(x) Exit\n"
    echo
    display_msg
    printf "Enter a command --> "
    return
}

function move_item_up () {
    if [ $item_to_prioritize -eq 0 ]; then
        return
    else
        item_to_exchange=$(( $item_to_prioritize-1 ))
        swapper=$item_to_prioritize
        swappee=$item_to_exchange
        TEMP_ITEMS=("${ITEMS[@]:0:$swappee}" "${ITEMS[$swapper]}" "${ITEMS[$swappee]}" \
        "${ITEMS[@]:$(($swapper + 1))}")
        ITEMS=("${TEMP_ITEMS[@]}")
        item_to_prioritize=$((item_to_prioritize-1))
    fi
}
    
    
function move_item_down () {
    if [[ $item_to_prioritize -eq ${#ITEMS[@]}-1 ]]; then
        return
    else
        item_to_exchange=$(( $item_to_prioritize+1 ))
        swapper=$item_to_prioritize
        swappee=$item_to_exchange
        TEMP_ITEMS=("${ITEMS[@]:0:$swapper}" "${ITEMS[$swappee]}" "${ITEMS[$swapper]}" \
        "${ITEMS[@]:$(($swappee + 1))}")
        ITEMS=("${TEMP_ITEMS[@]}")
        item_to_prioritize=$((item_to_prioritize+1))
    fi
}

function respond_to_priority_key_press () {
    read -s -n 1 key
    case $key in
        j|J) move_item_down;;
        k|K) move_item_up;;
        b|B) 
            item_to_prioritize=-1
            break;;
        *) bad_choice;;
    esac
    return
}

function select_item_to_prioritize () {
    clear
    echo
    show_todo_list
    echo
    while [[ $item_to_prioritize -gt -1 ]]; 
    do
            clear
            echo
            show_todo_list
            echo
            echo $item_to_prioritize "|" ${#ITEMS[@]}
            echo
            printf "Press (k)- up or (j)- down to prioritize the selection or (b)
            to go back --> "
            respond_to_priority_key_press
    done
    clear
    echo
    show_todo_list
    echo
    printf "PRIORITIZE AN ITEM\n"
    echo
    printf "$CANCEL\n"
    echo
    display_msg
    printf "Enter an item # to prioritize then press ENTER --> "
    return
}


function enter_prioritize_mode () {
    clear
    number_of_list_items=${#ITEMS[@]}
    while true
    do
        show_todo_list
        select_item_to_prioritize
        read answer
        MSG=
        case $answer in
            [1-"$number_of_list_items"] ) 
                item_to_prioritize=$(( $answer-1 ));;
            c|C) break;;
            *) bad_choice;;
        esac
    done
    return
}
#------------------------------------------------------------------------------
# MAIN LOGIC
#------------------------------------------------------------------------------

read_items_from_file
while true
do
    show_todo_list
    show_finished_items
    show_main_menu_options
    read -s -n 1 answer
    MSG=
    case $answer in
        a|A) add_item;;
        d|D) delete_item;;
        f|F) finish_item;;
        p|P) enter_prioritize_mode;;
        x|X) write_list_to_file;;

        *) bad_choice;;
    esac
done

